- style.css
多分意図と合ってると思います。ディスクリプションの英語は以下の意味です。
> Lightning はとてもシンプルでカスタマイズが簡単な、Bootstrapベースのテーマです。カスタム投稿タイプやカスタム分類とも親和性が高く、新しいのを追加した時にもパンくずや投稿がテンプレートファイルの追加や編集なしで綺麗に表示されます。
間違ってたら修正してください。
> style.css の Description と Tags をちょっとだけ書き換え

- .gitignore
- .travis.yml
- config.rb
- gulpfile.js
- package.json
travis使用への設定変更
- 全てのphpファイルのシンタックチェック
- design_skin/origin のscssコンパイル
- gulpのコンパイル
上記の動作をphp5.6,php7のそれぞれで確認し、全て成功すればビルド成功となります
> travisビルド設定の追加

- inc/customizer.php
> slide_count_max をフィルターフックで変更できるように修正

- inc/woocommerce/_scss/woo.scss
Please check following site, css.
https://wc.artws.info/product-category/woo-official-jp-suport/
> For Subscription Product type

- front-page.php
- page-lp-builder.php
- page-lp.php
- page-onecolumn.php
- page.php
- single.php
@drill-lancer 
なるほどテストしたら難しかったです（・ｗ・；
こんな感じで少しは短く書けるかなと。
追加箇所はこれで良いですよね？
> Feature/add article outer class #363 #369

- .phpcs.xml.dist
- .travis.yml
- bin/install-wp-tests.sh
- inc/layout-controller/functions-layout-controll.php
- phpunit.xml.dist
- tests/bootstrap.php
- tests/test-lightning_is_layout_onecolumn.php
- tests/test-lightning_is_subsection_display.php
- tests/test-sample.php
・テストファイルを再作成
・カラム設定のテストが完了しました。
> テストファイル更新＆テスト終了

- front-page.php
- gulpfile.js
- inc/vk-components/package/class-vk-component-posts.php
- index.php
追加例
```
function my_add_loop_ads($loop, $options){
global $vk_posts_loop_item_count;
if ( ( $vk_posts_loop_item_count % 3 ) == 0 ){
$loop .= '<div>追加'.$options['layout'].'</div>';
}
return $loop;
}
add_filter( 'vk_posts_loop_middle', 'my_add_loop_ads',10, 2 );
function my_lightning_add_loop_ads(){
global $lightning_loop_item_count;
if ( ( $lightning_loop_item_count % 3 ) == 0 ){
echo '<div>追加</div>';
}
}
add_action( 'lightning_loop_item_after', 'my_lightning_add_loop_ads' );
```
> 広告挿入用のフック追加 #363 #365

- functions-compatible.php
- inc/layout-controller/functions-layout-controll.php
- tests/test-lightning_is_layout_onecolumn.php
> オプションの優先度を変更

- inc/layout-controller/functions-layout-controll.php
- tests/test-lightning_is_layout_onecolumn.php
- tests/test-lightning_is_subsection_display.php
・テストファイルの show_on_front を修正
・is_home() と is_front_page() 周りのロジックを変更
・サイドバー周りのロジックの変更漏れの修正
> is_front_page をテストに適用+α

- inc/customize/customize-top-slide.php
- inc/vk-components/package/class-vk-component-mini-contents.php
- template-parts/slide-bs3.php
> スライドのエスケープを修正

- package-lock.json
- package.json
セキュリティアラートが出ていたため
https://github.com/vektor-inc/Lightning/network/dependencies
> nodeモジュールのアップデート

- package-lock.json
package-lock.jsonを作りなおしnode14に対応させました
テスト手順
1. チェックアウト
2. node_modulesを削除
3. ` npm install -D`
4. ビルドしてみる　`npm run build`
> node14に対応させる(再

- sidebar-page.php
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/517
> リスト内に親ページを追加

- inc/vk-css-optimize/package/class-vk-css-optimize.php
下記サイトで検証して上手く行ったバージョンです。
（LiteSpeed Cache + Cloudflare といった実用的な高速化もほどこしています。）
https://demo.drill-lancer.com/
> mixhost で動作確認したバージョン

- inc/vk-mobile-nav/package/class-vk-mobile-nav.php
/package//images/xxxx.svg -> /package/images/xxxx.svg
> Fix mobile nav menu svg path

- _g3/inc/ltg-g3-slider/package/class-ltg-g3-slider.php
- _g3/inc/vk-swiper/config.php
- _g3/inc/vk-swiper/package/class-vk-swiper.php
内容：
・Swiper の読み込み方法を修正
・Tree Shaking を適用
> Swiper の読み込み方法を修正

- _g3/inc/vk-swiper/package/class-vk-swiper.php
This reverts commit fa78f7c5169c2d5575c7b2b5b67529772bf3bbfe.
> Revert "Swiper の Tree Shaking の除外設定を追加"

- _g3/inc/ltg-g3-slider/package/class-ltg-g3-slider.php
- _g3/inc/vk-swiper/package/class-vk-swiper.php
> Swiper の Cube を許可するフィルターフックを追加

- inc/old-page-template.php
下記報告のエラーを修正したものになります。
https://trello.com/c/fGD151jx/3432-%E3%83%97%E3%83%A9%E3%82%A4%E3%83%99%E3%83%BC%E3%83%88%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%AE%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B-%E3%83%90%E3%82%B0%E3%81%AE%E4%BF%AE%E6%AD%A3%E6%96%B9%E6%B3%95%E3%81%A8lightning%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3
> 【確認待ち】【プライベートサポート】old-page-template.php のエラーを修正

- _g3/inc/vk-css-optimize/config.php
Reverts vektor-inc/lightning#731
> Revert "【確認待ち】スキン の CSS は Minify & インライン展開のみ適用"

- _g2/inc/vk-css-optimize/package/class-css-tree-shaking.php
- _g2/inc/vk-css-optimize/package/class-vk-css-optimize.php
- _g3/inc/vk-css-optimize/package/class-css-tree-shaking.php
- _g3/inc/vk-css-optimize/package/class-vk-css-optimize.php
- readme.txt
> Tree Shaking アップデート #851

- _g3/inc/vk-color-palette-manager/config.php
- _g3/tests/test-vk-wp-oembed-blog-card.php
https://github.com/vektor-inc/vk-color-palette-manager/pull/14
- Lightning のキーカラーを Color Palette Theme に属するように変更
- [Color Palette Manager](https://github.com/vektor-inc/vk-color-palette-manager/pull/14) でテーマのパレットを無効化するとキーカラーが表示されなくなるのを確認しました。
（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）
- [Color Palette Manager](https://github.com/vektor-inc/vk-color-palette-manager/pull/14) でテーマのパレットを無効化するとキーカラーが表示されなくなるのを確認お願いします。。
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】キーカラーのパレットを[color][palette][theme]に配属

- _g3/inc/vk-color-palette-manager/config.php
https://github.com/vektor-inc/lightning/issues/857
> [ 不具合修正 ][ カラーパレット ] 応急措置で戻し #857

- composer.json
- composer.lock
- readme.txt
> [ G3 ][ パンくずリスト ] 絞り込み検索でキーワードとの複合条件で検索した場合の表示不具合修正

- _g3/plugin-support/bbpress/functions-bbpress.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/893
> [ G3 ][ BBPress ] 表示ユーザー名取得エラー修正

- composer.json
- composer.lock
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/top%e3%83%9a%e3%83%bc%e3%82%b8%e3%82%b9%e3%83%a9%e3%82%a4%e3%83%89%e3%82%b7%e3%83%a7%e3%83%bc%e3%81%8c%e3%82%bf%e3%83%86%e3%81%ab%e4%b8%a6%e3%82%93%e3%81%a7%e3%81%97%e3%81%be%e3%81%86
- 上記お問い合わせに対応（Windows で XAMPP を使用したとき、パスがURLに置換されなくておかしくなるバグを修正）
- Swiper を 9.3.2 に更新
⇒大幅な変更はないため省略
- 実際に Windows ✕ XAMPP で確認
- スライダーブロックが正常に動くのを確認
- npm run phpunit が正常に動くのを確認
ローカル環境
- 実際に Windows ✕ XAMPP で確認（できれば）
- スライダーブロックが正常に動くのを確認
- npm run phpunit が正常に動くのを確認
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】Swiper を更新

- _g2/inc/vk-helpers/package/class-vk-helpers.php
- _g3/inc/vk-helpers/package/class-vk-helpers.php
- _g3/tests/test-vk-wp-oembed-blog-card.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/1036
少数にならないように VK_Helpers を調整
実装者が確認した手順を箇条書きで記載してください。
* PHP 8.2 の環境でエラーが出ない事を確認
> PHP8.2対応（Update VK_Helpers）

- _g2/inc/vk-components/package/class-vk-component-button.php
- _g2/inc/vk-components/package/class-vk-component-posts.php
- _g2/inc/vk-helpers/package/class-vk-helpers.php
- _g2/tests/test-button.php
- _g3/inc/vk-components/package/class-vk-component-button.php
- _g3/inc/vk-components/package/class-vk-component-posts.php
- _g3/inc/vk-helpers/package/class-vk-helpers.php
- _g3/tests/test-button.php
- _g3/tests/test-vk-wp-oembed-blog-card.php
- readme.txt
> VK_Component アップデート （ VK_Helpers の依存解除 ）

- _g2/inc/vk-helpers/package/class-vk-helpers.php
- _g3/inc/vk-helpers/package/class-vk-helpers.php
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/button-outline-hover-style
v15.9.4 の VK_Helpers::color_auto_modifi() の処理に不具合があったため修正
> [ G3 / G2 ][ Bug Fix ] Fix VK_Helpers::color_auto_modifi()

- _g2/plugin-support/bbpress/functions-bbpress.php
- _g3/plugin-support/bbpress/functions-bbpress.php
- readme.txt
https://github.com/vektor-inc/vws-forum/issues/49
- bbpress のトピックのタイトルを bbp_get_topic_title から取得するように変更
- https://github.com/vektor-inc/vws-forum/pull/52
=> 手動確認で十分そうなので省略
1. ローカル環境で [lightning](https://github.com/vektor-inc/lightning/pull/1042) と bbpress と [vws-forum](https://github.com/vektor-inc/vws-forum) を有効化する
2. 適当にフォーラムを作成
3. 記号を含むトピックタイトルを持つトピックを作成
4. 適当にトピックステータスを変更しそれがトピックタイトルに反映されるのを確認
ローカル環境
1. ローカル環境で [lightning](https://github.com/vektor-inc/lightning/pull/1042) と bbpress と [vws-forum](https://github.com/vektor-inc/vws-forum) を有効化する
2. 適当にフォーラムを作成
3. 記号を含むトピックタイトルを持つトピックを作成
4. 適当にトピックステータスを変更しそれがトピックタイトルに反映されるのを確認
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】bbpress のトピックのタイトルを bbp_get_topic_title から取得するように変更

- composer.json
- composer.lock
- readme.txt
- style.css
https://github.com/vektor-inc/font-awesome-versions/issues/22
> Font Awesome 6.4.2 対応 ( Supports the icon font of X )

- _g2/inc/vk-mobile-nav/vk-mobile-nav-config.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/1081
G3 と Katawara では 
```
$library_url = get_template_directory_uri() . '/inc/vk-mobile-nav/package';
```
だったが G2 では
```
$library_url = get_template_directory_uri() . '/inc/vk-mobile-nav/package/';
```
だったので G3 と Katawara に合わせるように修正
⇒ URL の帳尻合わせをしただけなので省略
Tree Shaking が ON の状態で G2 / G3 に切り替えても 
```
:root {
--vk-mobile-nav-menu-btn-bg-src: url("' . esc_url( $library_url . '/images/vk-menu-btn-black.svg' ) . '");
--vk-mobile-nav-menu-btn-close-bg-src: url("' . esc_url( $library_url . '/images/vk-menu-close-black.svg' ) . '");
--vk-menu-acc-icon-open-black-bg-src: url("' . esc_url( $library_url . '/images/vk-menu-acc-icon-open-black.svg' ) . '"); …
```
> 【確認待ち】VK Mobile Nav の不具合を修正

- composer.json
- composer.lock
- readme.txt
https://github.com/vektor-inc/vk-swiper/issues/3
Swiper を 11.0.2 に更新
=> Swiper を更新しただけなので省略
スライドが正常に動作するのを確認
ローカル環境
スライドが正常に動作するのを確認
---
* プルしたか？
* ビルドしたか？
> 【2人目確認待ち】Swiper を 11.0.2 に更新

- _theme.json
- readme.txt
グループブロックの背景画像指定機能対応
https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/
実装者が確認した手順を箇条書きで記載してください。
* WordPress 6.4 環境に指定
* 外観 > カスタマイズ > Lightning 機能設定 で theme.json を有効に設定
* グループブロックに背景画像指定のUIが表示されるか確認
レビュワーがどういう手順で何を確認して欲しいかを記載してください。
実装者確認手順に同じ
---
* プルしたか？
* ビルドしたか？
> 【2人目確認待ち】Added support for the background image feature in Group blocks, introduced in WordPress 6.4.

- composer.json
- composer.lock
- readme.txt
https://github.com/vektor-inc/vk-css-optimize/pull/15
https://github.com/vektor-inc/vk-blocks-pro/pull/1911
> Update css optimizer 0.2.2

- _theme.json
- readme.txt
> [ 6.5 ] Attend to backgroundSize

- _theme.json
- readme.txt
> [ G3 ][ 6.5 ] Attend to aspectRatio

- _g3/inc/template-tags.php
- readme.txt
- style.css
*
*
*
*
*
*
---
* プルしたか？
* ビルドしたか？
> [ Change version ] 15.25.1 / fix php warning

- _g2/functions.php
- _g2/inc/starter-content.php
- _g3/functions.php
- _g3/inc/starter-content.php
- readme.txt
6.7 で 翻訳関連の notice が発生しないように修正
> Fixed a translation-related notice that occurred in version 6.7.

- _theme.json
- readme.txt
https://github.com/vektor-inc/vk-patterns/issues/371#issuecomment-2487176292
WP6.7から追加されたタイポグラフィの「方向」オプションをテーマでサポートしました。
これにより、縦書きが簡単にできるようになります。
@kurudrive 問題ないかと思いますがもし何かありましたらお書きください。
→theme.jsonにサポートを追加しただけなのでスキップ。
WP6.7でタイポグラフィのオプションに「方向」が追加されていることを確認しました。
また、縦書きを選択した時に縦書きが機能していることを確認しました。
実装者と同じ確認を行ってください。
---
* プルしたか？
* ビルドしたか？
> [ WP6.7 ] タイポグラフィの「方向」オプションをサポートしました

- .github/workflows/build_check.yml
- .github/workflows/github_release.yml
- playwright.yml
Github ActionsのSet up jobで止まったため
GitHub Actions で廃止された actions/XXX@v2 を actions/XXX@v4 に更新 
@v4 は @v3 の改良版で後方互換性があり、GitHub 公式が @v4 への移行を推奨しているため、@v3を経由せず@v4に更新しました。
こちらが取り込まれたあと、テストが失敗しているブランチでも動くようにしてみます。
お一人で大丈夫かと思いますが何かありましたら2人確認にしてください。
- .github/workflows/ 内の全 .yml ファイルを確認
- GitHub に修正したファイルをプッシュ後、Actions の「Actions」タブでワークフローを実行
- すべてのワークフローが正常に完了することを確認
- このブランチで `npm run build` や `npm install` 、 `composer install` を行い、プラグインの動きなどに影響がないことを確認
このブランチで `npm run build` や `npm install` 、 `composer install` を行い、プラグインの動きなどに影響がないことを確認してください。
---
* プルしたか？
* ビルドしたか？
> GitHub Actionsの actions/XXX@v2 廃止に伴う修正 (@v4 に更新) 

- _g2/inc/vk-helpers/package/class-vk-helpers.php
- _g3/inc/vk-helpers/package/class-vk-helpers.php
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/107855
https://github.com/vektor-inc/vektor-wp-libraries/pull/149
> [ 不具合修正 ][ Helpers ] 存在しないタームのURLにアクセスされた場合のエラー修正

- _g3/assets/_scss/block/_block.scss
- _g3/assets/_scss/components/_slide.scss
- _g3/assets/_scss/project/_site-header.scss
- _g3/assets/_scss/wp-embed.scss
- readme.txt
`npm run build`の際に発生したwarningのうち、`mixed-decls`の警告を修正しました。
`mixed-decls`以外のエラーはBootstrapに関わっているため、今回はそのままにしておます。
Sassの将来のバージョンで予定されている変更に対応するため、ネストされたルール（@mediaなど）の後に書かれたCSSプロパティを前に移動する修正をしました。
`master`で出ていた、以下の箇所のエラーのwarningが`npm run build`で出なくなることを確認。
* `_g3/assets/_scss/components/_slide.scss`
* `_g3/assets/_scss/project/_site-header.scss`
* `_g3/assets/_scss/wp-embed.scss`
* `_g3/assets/_scss/block/_block.scss`
確認時はターミナルで以下のコマンドを打ち、何も出ない事を確認。
```
npx sass _g3/assets/_scss/style.scss --style=compressed 2>&1 | grep -E "(mixed-decls|slide\.scss|site-header\.scss|wp-embed\.scss|block\.scss)" | head -20
```
masterでは上記のコマンドを打った際に以下のようなメッセージが出ます。
```
DEPRECATION WARNING [mixed-decls]: Sass's behavior for …
```
> [ G3 ][ その他 ][ Sass mixed-decls警告を修正
