- functions.php
`$content_width`が機能していなかったので見てみたらローカルスコープのままでした。 :droplet:
> $content_width is global var

- functions.php
- header.php
WordPress 4.4よりwp_titleは非推奨になるよう。
`add_theme_support( 'title-tag' );`
https://core.trac.wordpress.org/changeset/35294
https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/
> WordPress 4.1以降の新しいタイトルタグ

- functions_helpers.php
https://wpdocs.osdn.jp/%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88%E3%82%BF%E3%82%B0/bloginfo
bloginfo()は常に単体で出力する関数です。echo文で出力する必要はありません。
get_bloginfo() を使うべきか、echo文を除去するか、あえて残すかは御判断ください。
> function bloginfo() no returns.

- functions.php
ウィジェット名の翻訳時に、翻訳者が何を翻訳しているのかわかりやすいようにプレースホルダとコメントを利用しました。
> Add placeholder and translator comment.

- inc/customize/customize-design.php
リンクテキストカラーの項目を追加しました。
CSS の読み込み位置は lightning_print_css_common の中に入れています。
> リンクテキストカラーを追加

- _g3/inc/ltg-g3-slider/package/class-ltg-g3-slider.php
- Slide transition time と同様にStop time.のテキストフィールドを追加
- オプションデータは669行目辺りで設定が書いてあったため不要でした
とりあえず翻訳はしなくて英語のままでOKとのことなので翻訳は出来ていません
> G3 スライドの静止時間が指定できないので、出来るようにする

- _g3/index.php
・Video Unit 用にスライド表示・非表示のフック ( lightning_default_slide_display ) を追加しました。
関連：https://github.com/vektor-inc/lightning/issues/595
> Video Unit 用にスライド表示・非表示のフックを追加

- _g2/functions.php
- _g2/inc/customize/customize-design.php
- _g2/inc/vk-css-optimize/package/class-css-tree-shaking.php
- _g2/inc/vk-css-optimize/package/class-vk-css-optimize.php
- _g3/functions.php
- _g3/inc/class-design-manager.php
- _g3/inc/customize/customize-design.php
- _g3/inc/vk-css-optimize/package/class-css-tree-shaking.php
- readme.txt
- style.css
【現状の問題点と解決策】
- 編集画面において ```enqueue_block_editor_assets``` は上部で ```add_editor_style``` は下部で読み込まれる
⇒両方書くと ```enqueue_block_editor_assets``` にで定義した CSS に ```wp_add_inline_style``` で引っ掛けても効かない
⇒```add_editor_style``` は Classic Editor 専用にすることで解決
---
【確認条件】
- プラグインを無効化した状態でテーマを Lightning にして確認
---
【確認事項】
- 編集画面でキーカラーが効くか否か
> 編集画面でキーカラーが反映されないのを修正

- _g3/inc/ltg-g3-slider/package/class-ltg-g3-slider.php
Lightning G3 のスライダーでボタンがない場合の文字の上でリンクが効かない不具合が修正されているか確認お願いします。
> 【確認待ち】[ 不具合修正 ][ G3 スライダー ] ボタンがない場合の文字の上でリンクが効かない不具合を修正

- _g3/inc/vk-css-optimize/config.php
CSS の不要な部分を削除する Tree Shaking は闇が深そうなので
スキンの CSS は Tree Shaking は適用せず Minify & インライン展開のみ適用するよう変更しました。
> 【確認待ち】スキン の CSS は Minify & インライン展開のみ適用

- _g3/functions.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/809
- wp-admin/widget.php を開いたときに lightning-js が読まれないように変更しました。
- セキュリティ面で  wp-admin のパス名を変えていることも想定し判定には admin_url() も採用しました。　
ウィジェット編集画面で lightning-js が読み込まれなくなったことを確認しました。
（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）
以下の確認をお願いします。
- ウィジェット編集画面で lightning-js が読み込まれなくなったこと
- コードレビュー
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】ウィジェット編集画面で lightning-js が読まれないように変更

- _g3/assets/_scss/project/_site-header.scss
そのままマージしていただいてもいいくらいの微修正です。
https://github.com/vektor-inc/lightning/issues/710
タブレットサイズ以下の場合に、テキストが折り返すように`white-space: normal;`を追加しました。
.site-header-logo{
@media ( max-width: $md-max ){
`white-space: normal;`
}
}
> 【確認待ち】タブレットサイズ以下でサイトタイトルテキストが長い場合見切れてしまうので追加

- _g2/front-page.php
- readme.txt
あー、
G3 から G2 に変更した時にリロードしてない時だけ $bootstrap の判定失敗するとかそんな感じっぽい。
> [ G2 ][ Bug fix ] Fix fatal error arise from bootstrap version version judgement on slider

- _g3/functions.php
- _theme.json
- readme.txt
https://wp.me/p2AvED-rDu
theme.json 有効でなくとも リンクカラーの設定と線の設定が使えるように
> [ G3 (no-theme.json) ] Support link color and border.

- _g3/inc/template-tags.php
- readme.txt
https://github.com/vektor-inc/lightning-g3-pro-unit/issues/222
- ページヘッダーの処理が走っている際に `get_the_author()` が機能していなかったので遠回しの記述に変更
=> 投稿者情報の取得方法を変更しただけなので省略
- Pro 環境でページヘッダーにメタ情報が載る設定で投稿者情報がページヘッダーに載るのを確認
ローカル環境
- Pro 環境でページヘッダーにメタ情報が載る設定で投稿者情報がページヘッダーに載るのを確認
---
* プルしたか？
* ビルドしたか？
> 【確認待ち】投稿のメタ情報を修正

- _g3/inc/template-tags.php
- readme.txt
VK Blocks Pro のユニットテストで 
1) Test_PHP_Fatal_Error::test_run_php_fatal_error
Trying to get property 'display_name' of non-object
くらうため、the_post() 経由するように修正
> lightning_get_entry_meta の author 取得処理修正

- _g3/template-parts/entry.php
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/post-bottom-meta-taxonomy-list-class
投稿本文下 taxonomy リストにタクソノミー識別クラスを追加
> [ G3 ] 投稿 本文下部 タクソノミーリストにタクソノミー識別クラスを追加

- _g3/template-parts/page-header.php
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/page-header-entry-meta-allow-style
> ■ 期待する動作
> フィルターフックでカスタマイズして
> ページヘッダーの entry-meta の中に指定した style 属性が
> wp_kses によって除去されずに出力されるようにしてほしい。
> 
> 添付画像(1)をご参照ください。
> 
> ■ 自分で試した事
> /wp-content/themes/lightning/_g3/template-parts/page-header.php
> に以下の行を追加したら希望通りに出力されるようになりました。
> 
> 'style' => array(),
> 
> 添付画像(2)をご参照ください。
> 
> ■ その他特記事項
> カスタム投稿タイプ「賃貸物件」のカスタム分類「設備」を
> 物件名といっしょにページヘッダーに表示するカスタマイズを行っています。
> 
> カスタム分類「設備」に設定した色を style 属性により表示したいのですが、
> $allowed_html に ‘style’ が含まれていないために
> フックで指定した style 属性が除去されてしまいます。
> 
> page-header.php に 'style' => array(), を追加していただけると
> ありがたいです。
> 
> ご検討のほどよろしくお願いします。
> 
ページヘッダーの entry-meta の span タグに style を許可
> ページヘッダーの entry-meta の span タグに style を許可

- _g3/assets/_scss/project/_site-header.scss
- readme.txt
#1118 
* .site-header--layout--nav-float .site-header-logo a に「ヘッダーレイアウト」の「ナビゲーション回り込み」の時のロゴのリンクエリアが広くならないための設定をしました。
実装者が確認した手順を箇条書きで記載してください。
* 外観 > カスタマイズ > Lightning ヘッダー設定 > ヘッダーレイアウト「ナビゲーション回り込み」で保存。
* 上記設定保存後、ヘッダーロゴのリンクエリアがロゴの表示範囲になっていることを確認。
* ヘッダーレイアウト「ナビゲーション回り込み & 縦書き (β)」でも同様の現象となっていたが上記CSS変更で対応できていることを確認。
* ロゴ画像がない状態でも不具合がないことを確認。
* ブラウザはGoogle Chrome、Firefox、Safariで確認。
* ブラウザのモードは通常、シークレットモード、ゲストモードで確認。
（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）
レビュワーがどういう手順で何を確認して欲しいかを記載してください。
* 外観 > カスタマイズ > Lightning ヘッダー設定 > ヘッダーレイアウト「ナビゲーション回り込み」「ナビゲーション回り込み & 縦書き (β)」で保存してください。
* 上記設定保存後、ヘッダーロゴのリンクエリアがロゴの表示範囲になっていることを確認ください。
* ロゴ画像がない状態でも不具合がないことを確認ください。
---
* …
> [ ヘッダーレイアウト ] ナビゲーション回り込みの時のロゴのリンクエリアが広い点を修正

- copy-files.js
- gulpfile.mjs
- package-lock.json
- package.json
npm run dist してファイルはコピーされるが、画像が壊れてしまう
dist 処理を gulp ではなく copy-files.js に変更
> dist コマンドで画像ファイルが壊れてしまうため dist 処理を変更

- _g2/assets/_scss/block/_block.scss
カバーの幅で中の要素が切れてしまうので切れないように修正
```
<div class="wp-block-cover is-light" style="padding-right:0;padding-left:0;min-height:50px"><span aria-hidden="true" class="wp-block-cover__background has-pale-cyan-blue-background-color has-background-dim-100 has-background-dim"></span><div class="wp-block-cover__inner-container">
<div class="wp-block-columns alignwide" style="border-width:1px">
<div class="wp-block-column">
<p>通常幅カバー &gt; 幅広カラム</p>
</div>
<div class="wp-block-column">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut</p>
</div>
<div class="wp-block-column">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod …
```
> [ G2 ] カバーブロック内の幅広が編集画面で切れる不具合を修正

- _g3/plugin-support/woocommerce/functions-woo.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/1178
WooCommerce用のファイル読み込みパス修正
> Fixed an issue where the WooCommerce CSS file failed to load on the edit screen when using WooCommerce.

- .github/workflows/build_check.yml
CSS Optimize を無効化している都合上 Playwright のテストが通らないため一旦削除
```
- name: Install dependencies ////////////////////////
run: npm ci
- name: Install Playwright Browsers
run: npx playwright install --with-deps
- name: Run Playwright tests
run: npx playwright test --trace on --project=chromium
- uses: actions/upload-artifact@v3
if: always()
with:
name: playwright-report
path: playwright-report/
retention-days: 30
```
> Playwright テスト無効化

- _g3/inc/template-tags.php
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/104402
投稿者の画像を取得する際に、まず VK Post Author Display で登録した画像があれば取得する。
しかしながら、画像のファイル自体を削除されてしまうと、画像データの配列が取得できずに、warning が発生する。
プロフィール画像を取得失敗した場合の処理を追加
* master ブランチ
* G3 Pro Unit を有効化
* プラグイン VK Post Author Display をインストール・有効化
* ユーザー編集画面でプロフィール画像を登録
* プロフィール画像を登録したユーザーで記事を投稿
* 投稿詳細ページを表示 -> 普通に表示される
* プロフィール編集画面からメディアライブラリを開いて画像を削除（★プロフィール自体は保存しない）
* 投稿詳細ページでWarning が表示される
* このブランチに切り替え -> Warning が消える
実装者に同じ
---
* プルしたか？
* ビルドしたか？
> [ G3 ][ Bug fix ] Fix profile image warning

- _g3/assets/_scss/overwrite/_vk-components.scss
- readme.txt
https://discord.com/channels/1086176580675584011/1380368043129049200/1380368043129049200
border-topに太さやスタイルの指定がないため、線が表示されていませんでしたのでそれを修正しました。
お一人で大丈夫かと思います。
このプルリクを npm run build した後、Lightining G3で投稿やカスタム投稿タイプのアーカイブを開き、最初に出る記事上の線が出なくなっているのを確認。
実装者と同じ確認をお願いいたします。
---
* プルしたか？
* ビルドしたか？
> [ G3 ][ デザイン不具合修正 ] アーカイブの最初に出る記事上の線が出なくなっていたのを修正しました

- _g2/library/bootstrap-4/css/bootstrap.min.css
- _g2/library/bootstrap-4/scss/bootstrap.scss
- readme.txt
https://github.com/vektor-inc/lightning-pro/pull/304/files
> [ G2 ][ Bug fix ] Fix an issue where Bootstrap CSS is not loaded in the iframe of the block editor on the edit screen.

- _g3/inc/vk-wp-oembed-blog-card/package/class-vk-wp-oembed-blog-card.php
- readme.txt
https://github.com/vektor-inc/lightning/issues/1258
get_the_excerpt() 以外の方法で抜粋を取得するように変更
1. 記事Aに記事BのURLを埋め込み
2. 記事Bに記事AのURLを埋め込み
3. ブログカードの処理が無限ループでメモリオーバーでエラーになる
4. このブランチ版に切り替え
5. 記事A，記事Bともに正常に表示されるようになる事を確認
---
* プルしたか？
* ビルドしたか？
> [ 不具合修正 ] 同じサイト内の記事どうしで埋め込むとブログカードの処理が無限ループになりメモリオーバーでエラーになる不具合を修正
